BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Report] ALTER COLUMN [TITLE] NVARCHAR(10) NULL;
ALTER TABLE [dbo].[Report] ALTER COLUMN [RANK] NVARCHAR(20) NULL;
ALTER TABLE [dbo].[Report] ALTER COLUMN [FIRSTNAME] NVARCHAR(60) NULL;
ALTER TABLE [dbo].[Report] ALTER COLUMN [LASTNAME] NVARCHAR(60) NULL;
ALTER TABLE [dbo].[Report] ALTER COLUMN [EST_TITLE] NVARCHAR(10) NULL;
ALTER TABLE [dbo].[Report] ALTER COLUMN [EST_NAME] NVARCHAR(100) NULL;
ALTER TABLE [dbo].[Report] ALTER COLUMN [ADD_NO] NVARCHAR(30) NULL;
ALTER TABLE [dbo].[Report] ALTER COLUMN [BUILDING] NVARCHAR(60) NULL;
ALTER TABLE [dbo].[Report] ALTER COLUMN [ROOM] NVARCHAR(30) NULL;
ALTER TABLE [dbo].[Report] ALTER COLUMN [STREET] NVARCHAR(50) NULL;
ALTER TABLE [dbo].[Report] ALTER COLUMN [BLK] NVARCHAR(30) NULL;
ALTER TABLE [dbo].[Report] ALTER COLUMN [SOI] NVARCHAR(30) NULL;
ALTER TABLE [dbo].[Report] ALTER COLUMN [SUB_DIST] NVARCHAR(30) NULL;
ALTER TABLE [dbo].[Report] ALTER COLUMN [DISTRICT] NVARCHAR(30) NULL;
ALTER TABLE [dbo].[Report] ALTER COLUMN [PROVINCE] NVARCHAR(30) NULL;
ALTER TABLE [dbo].[Report] ALTER COLUMN [POST_CODE] NVARCHAR(5) NULL;
ALTER TABLE [dbo].[Report] ALTER COLUMN [TEL_NO] NVARCHAR(20) NULL;
ALTER TABLE [dbo].[Report] ALTER COLUMN [E_MAIL] NVARCHAR(30) NULL;
ALTER TABLE [dbo].[Report] ALTER COLUMN [WEBSITE] NVARCHAR(30) NULL;
ALTER TABLE [dbo].[Report] ALTER COLUMN [SOCIAL] NVARCHAR(30) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
