import { Metadata } from "next";
import { Sarabun } from "next/font/google";

const sarabun = Sarabun({ subsets: ["thai"], weight: "500" });

export const metadata: Metadata = {
  title: "สำรวจยอดขายรายไตรมาส",
  description: "Generated by create next app",
};

export default function SearchLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div
      className={`${sarabun.className} flex flex-col max-w-[1300px] mx-auto text-gray-500`}
    >
      <div className="sm:px-16 md:px-24 px-6 py-5">
        <div className="pt-8">{children}</div>
      </div>
    </div>
  );
}
