import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="w-full max-w-[1300px] mx-auto">
      <div className="sm:px-16 md:px-24 px-6 py-5 pt-8">{children}</div>
    </div>
  );
}
