#!/bin/bash

echo DATABASE_URL=$DATABASE_URL >> .env
echo JWT_SECRET=$JWT_SECRET >> .env
echo NEXTAUTH_SECRET=$NEXTAUTH_SECRET >> .env
echo NEXTAUTH_URL=$NEXTAUTH_URL >> .env
echo NEXT_PUBLIC_CALLBACK_URL=$NEXT_PUBLIC_CALLBACK_URL >> .env
echo JWT_SECRET=$JWT_SECRET >> .env