import type { Metadata } from "next";
// import { Sarabun } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";
import { Toaster } from "sonner";
import AuthProvider from "@/components/AuthProvider";
import Navbar from "@/components/Navbar";
import FilterProvider from "@/context";

// const sarabun = Sarabun({
//   subsets: ["thai"],
//   weight: "500",
//   display: "swap",
//   adjustFontFallback: false,
// });

export const metadata: Metadata = {
  title: "สำรวจยอดขายรายไตรมาส",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        // className={`${sarabun.className} min-h-screen h-full mx-auto text-gray-500`}
        className={`min-h-screen h-full mx-auto text-gray-500`}
      >
        {/* <ConfigProvider
          theme={{
            token: {
              fontFamily: sarabun.style.fontFamily,
              colorText: "text-gray-500",
            },
          }}
        > */}
        <AuthProvider>
          <FilterProvider>
            <Toaster richColors={true} position="top-right" />
            <Navbar />
            {children}
          </FilterProvider>
        </AuthProvider>
        {/* </ConfigProvider> */}
      </body>
    </html>
  );
}
