import type { Metadata } from "next";
import { Sarabun } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";
import { Toaster } from "sonner";

const sarabun = Sarabun({ subsets: ["thai"], weight: "500" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${sarabun.className} min-h-screen flex flex-col max-w-[1300px] mx-auto text-gray-500`}
      >
        <ConfigProvider
          theme={{
            token: {
              fontFamily: sarabun.style.fontFamily,
              colorText: "text-gray-500",
            },
          }}
        >
          <Toaster richColors={true} position="top-right" />
          <div className="sm:px-16 md:px-24 px-6 py-5">
            <div className="pt-8">{children}</div>
          </div>
        </ConfigProvider>
      </body>
    </html>
  );
}
