-- AlterTable
ALTER TABLE "Report" ALTER COLUMN "ID" SET DATA TYPE TEXT,
ALTER COLUMN "STO" SET DATA TYPE TEXT;

-- AddForeignKey
ALTER TABLE "Report" ADD CONSTRAINT "Report_ID_YR_fkey" FOREIGN KEY ("ID", "YR") REFERENCES "ReportStatus"("ID", "year") ON DELETE RESTRICT ON UPDATE CASCADE;
