BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Control] ALTER COLUMN [firstname] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Control] ALTER COLUMN [lastname] NVARCHAR(1000) NULL;

-- AlterTable
ALTER TABLE [dbo].[Report] ALTER COLUMN [FIRSTNAME] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Report] ALTER COLUMN [LASTNAME] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Report] ALTER COLUMN [LG1] NVARCHAR(1000) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
